sudo: required
addons:
  chrome: stable

dist: xenial

services:
  - xvfb

language: node_js

node_js:
  - "8.9.1"

before_install:
  - curl https://install.meteor.com | /bin/sh
  - export PATH="$HOME/.meteor:$PATH"

cache:
  directories:
    - ~/.npm
    - "node_modules"

notifications:
  email: false

before_script:
  - sleep 3

script:
  - meteor create --release 1.8.1 --bare test
  - cd test
  - meteor npm i --save selenium-webdriver@3.6.0 chromedriver@2.36.0 simpl-schema chai meteor-apollo-accounts
  - meteor npm i -S graphql graphql-load apollo-server-express uuid graphql-tools graphql-type-json apollo-live-server apollo-link-schema react-dom react-router react-apollo react
  - meteor npm i -S apollo-live-client apollo-upload-client apollo-client graphql-tag apollo-cache-inmemory apollo-link apollo-link-http apollo-link-ws apollo-morpher subscriptions-transport-ws
  - METEOR_PACKAGE_DIRS="../" TEST_BROWSER_DRIVER=chrome meteor test-packages --once --driver-package meteortesting:mocha ../
